server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017
      database: xc_cms
